### ISSUE TITLE
Cropped version not displaying on frontend

### ISSUE THREAD

**Issue by beliven-fabrizio-gortani** [tv2regionerne/statamic-image-cropper#7]
I've the same problem. I've declared `16_9` and `freeform` dimensions and inside the control panel the field work as expected, but in the frontend it doesn't work.

In the CP I've following situation:

<img width="1378" alt="image" src="https://github.com/tv2regionerne/statamic-image-cropper/assets/99825015/aab1a6fb-949d-4acf-9229-bab0f56f6b72">

and in the frontend this one:

<img width="606" alt="image" src="https://github.com/tv2regionerne/statamic-image-cropper/assets/99825015/d78498f2-d1dd-48bc-b30c-37f4ee278659">

In the screen you can see the crop is ignored

Below the code used in FE:

```html
<img src="{{ glide:immagine_card :crop="crops:freeform:crop" }}"  alt="{{ immagine_card:alt }}"  />
```
Of course I've set the dimension `freeform` in the field section:

<img width="877" alt="image" src="https://github.com/tv2regionerne/statamic-image-cropper/assets/99825015/d066d5bb-5012-49d8-ad3e-b4dcaaaf8a59">

**Comment by sylvesterdamgaard** [comment]
I also replied on your other post, but let's keep it here to prevent cross posting.

I will make a test using the freeform config tomorrow and let you know of the results.
We don't use the freeform option in our sites, but only fixed dimension keys. Do the 16_9 dimension work for you?
Could you share the value of the crops:freeform:crop with me from the above example?

**Comment by beliven-fabrizio-gortani** [comment]
I've tried the 16_9 but it doesn't work! Here's the output..

```
{{glide:immagine_card :crop="crops:16_9:crop"}}
// output
/img/asset/YXNzZXRzL2JpdHJvbmljLTE2LTJfMDEuanBn?s=a52ae0457b16b5d67ed31c11db9c3f18
```

The freeform 

```
{{glide:immagine_card :crop="crops:freeform:crop"}}
// output
/img/asset/YXNzZXRzL2JpdHJvbmljLWYxM18wMS5qcGc=?s=4bfcf6bcdf4ded4f2f91324c81c65639
```

**Comment by sylvesterdamgaard** [comment]
I just setup a test and it's working as expected.
Is the Cropper field's handle named `crops` in your blueprint?

https://github.com/tv2regionerne/statamic-image-cropper/assets/2431914/f42f5593-d215-4470-a3dc-d836ffb730b5

### Antlers code
`<img src="{{ glide:image :crop="cropper:freeform:crop" }}"  alt="{{ image:alt }}"  />`

### Blueprint
```yaml
title: Page
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: image
            field:
              max_files: 1
              mode: list
              container: assets
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: image
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: cropper
            field:
              show_details: true
              source: image
              mode: manual
              dimensions:
                '16_9': 16/9
                freeform: Free
              type: image_cropper
              display: Cropper
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
```
